import { describe, it, expect, beforeAll } from "vitest";
import { start, ProgramTestContext } from "solana-bankrun";
import {
  PublicKey,
  Transaction,
  TransactionInstruction,
} from "@solana/web3.js";
// @ts-ignore -- snarkjs has no types
import * as snarkjs from "snarkjs";
import path from "path";
import { buildInstructionData, SnarkjsPlonkProof } from "./serialize";

const PROGRAM_ID = new PublicKey(
  Buffer.from([
    0x0b, 0x56, 0x00, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45,
    0x67, 0x89, 0xab, 0xcd, 0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
    0xef, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd,
  ]),
);

// Circuit build artifacts are in the root build/ directory (generated by `just build-test-circuit`)
const PROJECT_ROOT = path.resolve(__dirname, "../..");
const WASM_PATH = path.join(
  PROJECT_ROOT,
  "build/multiplier_js/multiplier.wasm",
);
const ZKEY_PATH = path.join(PROJECT_ROOT, "build/multiplier.zkey");

const COMPUTE_MAX_UNITS = 1_400_000n;

async function generateProof(
  a: string,
  b: string,
): Promise<{ proof: SnarkjsPlonkProof; publicSignals: string[] }> {
  const { proof, publicSignals } = await snarkjs.plonk.fullProve(
    { a, b },
    WASM_PATH,
    ZKEY_PATH,
  );
  return { proof, publicSignals };
}

async function sendVerifyTx(
  ctx: ProgramTestContext,
  instructionData: Buffer,
): Promise<{ success: boolean; logs: string[] }> {
  const client = ctx.banksClient;
  const payer = ctx.payer;

  const ix = new TransactionInstruction({
    programId: PROGRAM_ID,
    keys: [],
    data: instructionData,
  });

  const tx = new Transaction();
  tx.add(ix);
  const [blockhash] = (await client.getLatestBlockhash())!;
  tx.recentBlockhash = blockhash;
  tx.feePayer = payer.publicKey;
  tx.sign(payer);

  const result = await client.tryProcessTransaction(tx);
  const logs = result.meta?.logMessages ?? [];
  return { success: result.result === null, logs };
}

describe("PLONK on-chain verification with dynamic snarkjs proofs", () => {
  let ctx: ProgramTestContext;

  beforeAll(async () => {
    ctx = await start(
      [{ name: "integration_program", programId: PROGRAM_ID }],
      [],
      COMPUTE_MAX_UNITS,
    );
  });

  it("verifies a valid proof (a=3, b=11 -> c=33)", async () => {
    const { proof, publicSignals } = await generateProof("3", "11");
    expect(publicSignals).toEqual(["33"]);

    const data = buildInstructionData(proof, publicSignals);
    const { success, logs } = await sendVerifyTx(ctx, data);

    expect(success).toBe(true);
    expect(logs.some((l) => l.includes("verified successfully"))).toBe(true);
  });

  it("verifies a valid proof with different inputs (a=7, b=13 -> c=91)", async () => {
    const { proof, publicSignals } = await generateProof("7", "13");
    expect(publicSignals).toEqual(["91"]);

    const data = buildInstructionData(proof, publicSignals);
    const { success, logs } = await sendVerifyTx(ctx, data);

    expect(success).toBe(true);
    expect(logs.some((l) => l.includes("verified successfully"))).toBe(true);
  });

  it("rejects a proof with tampered public signals", async () => {
    const { proof } = await generateProof("3", "11");
    const tamperedSignals = ["99"];

    const data = buildInstructionData(proof, tamperedSignals);
    const { success } = await sendVerifyTx(ctx, data);

    expect(success).toBe(false);
  });
});
