use borsh::BorshDeserialize;
use plonk_solana::{Fr, Proof};

use solana_program::{
    account_info::AccountInfo, entrypoint, entrypoint::ProgramResult, msg,
    program_error::ProgramError, pubkey::Pubkey,
};

// Generated by build.rs from tests/fixtures/data/verification_key.json
include!(concat!(env!("OUT_DIR"), "/verifying_key.rs"));

entrypoint!(process_instruction);

#[derive(BorshDeserialize, borsh::BorshSerialize)]
pub struct VerifyInstruction {
    pub public_inputs: Vec<Fr>,
    pub proof: Proof,
}

fn process_instruction(
    _program_id: &Pubkey,
    _accounts: &[AccountInfo],
    instruction_data: &[u8],
) -> ProgramResult {
    let ix = VerifyInstruction::try_from_slice(instruction_data)
        .map_err(|_| ProgramError::InvalidInstructionData)?;

    run_verify(ix)
}

#[inline(never)]
fn run_verify(ix: VerifyInstruction) -> ProgramResult {
    let vk = verifying_key();

    match ix.public_inputs.len() {
        1 => plonk_solana::verify_unchecked(&vk, &ix.proof, &[ix.public_inputs[0]]),
        _ => {
            msg!(
                "Unsupported number of public inputs: {}",
                ix.public_inputs.len()
            );
            return Err(ProgramError::InvalidInstructionData);
        }
    }
    .map_err(|e| {
        msg!("PLONK verification failed: {}", e);
        ProgramError::Custom(u32::from(e))
    })?;

    msg!("PLONK proof verified successfully");
    Ok(())
}
